services:
  metastore:
    image: apache/hive/standalone-metastore:latest
    command: >
      bin/start-metastore 
        --hiveconf javax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore
        --hiveconf javax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        --hiveconf javax.jdo.option.ConnectionUserName=metastore_user
        --hiveconf javax.jdo.option.ConnectionPassword=metastore_user
    depends_on:
      postgres:
        condition: service_started
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=metastore_user
      - POSTGRES_PASSWORD=metastore_user
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./hive/standalone-metastore/src/main/sql/postgres/hive-schema-3.1.0.postgres.sql:/docker-entrypoint-initdb.d/hive-schema-3.1.0.postgres.sql

volumes:
  metastore-init:
  postgres-data: